
CREATE TABLE ROLES (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE USERS (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    role_id BIGINT NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_users_roles 
        FOREIGN KEY (role_id) REFERENCES ROLES(id) 
        ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE VAULTS (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    root_path VARCHAR(512) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_vaults_users 
        FOREIGN KEY (user_id) REFERENCES USERS(id) 
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE NOTES (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    vault_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    relative_path VARCHAR(512) NOT NULL,
    content TEXT,
    is_wiki_import BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_notes_vaults 
        FOREIGN KEY (vault_id) REFERENCES VAULTS(id) 
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE NOTE_LINKS (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    source_note_id BIGINT NOT NULL,
    target_note_id BIGINT NOT NULL,
    link_type VARCHAR(50) NOT NULL DEFAULT 'internal',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_links_source_note 
        FOREIGN KEY (source_note_id) REFERENCES NOTES(id) 
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_links_target_note 
        FOREIGN KEY (target_note_id) REFERENCES NOTES(id) 
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TAGS (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    vault_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT fk_tags_vaults 
        FOREIGN KEY (vault_id) REFERENCES VAULTS(id) 
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE NOTE_TAGS (
    note_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    PRIMARY KEY (note_id, tag_id),
    CONSTRAINT fk_notetags_notes 
        FOREIGN KEY (note_id) REFERENCES NOTES(id) 
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_notetags_tags 
        FOREIGN KEY (tag_id) REFERENCES TAGS(id) 
        ON DELETE CASCADE ON UPDATE CASCADE
);
